[package]
name = "zed_http"
version = "0.1.0"
edition = "2021"
publish = false
license = "Apache-2.0"


[lib]
path = "src/http.rs"
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
xdg = "3.0.0"
zed_extension_api = "0.7"
