id = "http-runner"
name = "http-runner"
description = "Fully support for .http files"
version = "1.0.0"
schema_version = 1
authors = ["bjqf0724@gmail.com"]
repository = "https://github.com/Brayan-724/zed-http-runner"

[language_servers.http]
name = "http"
language = "http"

[grammars.http]
repository = "http://github.com/rest-nvim/tree-sitter-http"
commit = "e061995f0caf2fa30f68fa1fdf2c08bcbd4629a8"
